nohup: ignoring input
emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0
Embedding data...
Transforming tweets with BERTweet...
  0%|          | 0/7 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
 71%|███████▏  | 5/7 [00:00<00:00, 45.86it/s]100%|██████████| 7/7 [00:00<00:00, 38.20it/s]
emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0
Embedded data saved at data/embedded_data/BERTweet2/train_tweets_embedded.csv
Transforming tweets with BERTweet...
  0%|          | 0/10 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
 50%|█████     | 5/10 [00:00<00:00, 49.10it/s]100%|██████████| 10/10 [00:00<00:00, 44.48it/s]100%|██████████| 10/10 [00:00<00:00, 41.38it/s]
Embedded data saved at data/embedded_data/BERTweet2/eval_tweets_embedded.csv
Data embedded and saved in {'processed': 'base_better_preprocessing', 'embedded': 'BERTweet2', 'predictions': 'base_predictions'}
Loading data from BERTweet2...
Traceback (most recent call last):
  File "/Data/ariane/Challenge_inf554/main.py", line 62, in <module>
    main()
  File "/Data/ariane/Challenge_inf554/main.py", line 25, in main
    X, y = load_embedded_data(config['data_paths']['embedded'], 'train_tweets')
  File "/Data/ariane/Challenge_inf554/embeddings/__init__.py", line 31, in load_embedded_data
    df = pd.read_csv(f"data/embedded_data/{embedded_folder}/{raw_folder}.csv")
  File "/users/eleves-b/2022/emile.bornand/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/users/eleves-b/2022/emile.bornand/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/users/eleves-b/2022/emile.bornand/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/users/eleves-b/2022/emile.bornand/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/users/eleves-b/2022/emile.bornand/.local/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/embedded_data/BERTweet2/train_tweets.csv'
